In [2]:
import numpy as np
print("WELCOME TO NUMPY!")

WELCOME TO NUMPY!


In [2]:
#1
def abc():print("Hello World") #Numpy
    
abc()

Hello World


In [3]:
#2
l = [7,8,6]
print(np.sum(l))


21


In [4]:
#3
l1 = np.arange(1000)
%time l1 + 6

Wall time: 0 ns


array([   6,    7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
         17,   18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
         28,   29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
         39,   40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
         50,   51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
         61,   62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
         72,   73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
         83,   84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
         94,   95,   96,   97,   98,   99,  100,  101,  102,  103,  104,
        105,  106,  107,  108,  109,  110,  111,  112,  113,  114,  115,
        116,  117,  118,  119,  120,  121,  122,  123,  124,  125,  126,
        127,  128,  129,  130,  131,  132,  133,  134,  135,  136,  137,
        138,  139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
        149,  150,  151,  152,  153,  154,  155,  1

In [5]:
#4
print("Dimension:", l1.ndim)

Dimension: 1


In [6]:
#5
print("Type:", l1.dtype)

Type: int32


In [7]:
#6
print("Size:", l1.size)

Size: 1000


In [8]:
#7
print("Itemsize:", l1.itemsize)

Itemsize: 4


In [9]:
#8
print("Shape:", l1.shape)

Shape: (1000,)


In [10]:
#9
print(l)

[7, 8, 6]


In [16]:
#10
l1 = np.arange(1,13).reshape((4,3))
print(l1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
#11

l1 = np.arange(1,28).reshape((3,3,3))
print(l1)
l1[1,2,1]


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


17

In [19]:
#12

l1 = np.random.randn(3,3,3)

print(l1)

[[[-0.66868716  0.27867658  0.31579772]
  [ 0.76998254  0.10660533 -1.77836757]
  [-1.86339715  0.92210264 -0.06802301]]

 [[-1.09679897 -0.33323126  0.96310615]
  [ 0.42191647 -1.28114044  0.04720605]
  [ 1.59508754  0.28173137 -1.94984237]]

 [[ 1.7106248   0.37819837 -1.76033544]
  [-2.21959849 -0.44574308  0.85015246]
  [-1.06757188 -0.46233773  0.54228051]]]


In [20]:
#13
l1 + 2


array([[[ 1.33131284,  2.27867658,  2.31579772],
        [ 2.76998254,  2.10660533,  0.22163243],
        [ 0.13660285,  2.92210264,  1.93197699]],

       [[ 0.90320103,  1.66676874,  2.96310615],
        [ 2.42191647,  0.71885956,  2.04720605],
        [ 3.59508754,  2.28173137,  0.05015763]],

       [[ 3.7106248 ,  2.37819837,  0.23966456],
        [-0.21959849,  1.55425692,  2.85015246],
        [ 0.93242812,  1.53766227,  2.54228051]]])

In [21]:
#14
l1 * 2


array([[[-1.33737432,  0.55735316,  0.63159544],
        [ 1.53996508,  0.21321065, -3.55673515],
        [-3.7267943 ,  1.84420529, -0.13604602]],

       [[-2.19359794, -0.66646253,  1.92621229],
        [ 0.84383294, -2.56228089,  0.09441211],
        [ 3.19017508,  0.56346275, -3.89968474]],

       [[ 3.4212496 ,  0.75639675, -3.52067089],
        [-4.43919697, -0.89148616,  1.70030492],
        [-2.13514376, -0.92467546,  1.08456101]]])

In [22]:
#15
l1 / 2


array([[[-0.33434358,  0.13933829,  0.15789886],
        [ 0.38499127,  0.05330266, -0.88918379],
        [-0.93169857,  0.46105132, -0.0340115 ]],

       [[-0.54839949, -0.16661563,  0.48155307],
        [ 0.21095823, -0.64057022,  0.02360303],
        [ 0.79754377,  0.14086569, -0.97492118]],

       [[ 0.8553124 ,  0.18909919, -0.88016772],
        [-1.10979924, -0.22287154,  0.42507623],
        [-0.53378594, -0.23116887,  0.27114025]]])

In [23]:
#16
l1 ** 2


array([[[4.47142519e-01, 7.76606361e-02, 9.97282012e-02],
        [5.92873110e-01, 1.13646956e-02, 3.16259123e+00],
        [3.47224893e+00, 8.50273284e-01, 4.62712965e-03]],

       [[1.20296798e+00, 1.11043075e-01, 9.27573448e-01],
        [1.78013506e-01, 1.64132084e+00, 2.22841161e-03],
        [2.54430426e+00, 7.93725665e-02, 3.80188526e+00]],

       [[2.92623721e+00, 1.43034009e-01, 3.09878087e+00],
        [4.92661744e+00, 1.98686894e-01, 7.22759205e-01],
        [1.13970972e+00, 2.13756178e-01, 2.94068148e-01]]])

In [24]:
#17
print(type(l1))

<class 'numpy.ndarray'>


In [25]:
#18
a = np.array([6,8])
a.itemsize

4

In [28]:
#19
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [29]:
#20
a.shape

(2,)

In [30]:
#21

np.zeros((a.shape))

array([0., 0.])

In [31]:
#22
np.zeros_like(a)


array([0, 0])

In [32]:
#23
b = np.ones((6,3))
b


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
#24
b = np.ones_like(a)
b

array([1, 1])

In [34]:
#25
b = np.ones_like(a) * 12 
b

array([12, 12])

In [36]:
#26
b = np.full((6,6), 10)
b

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [37]:
#27
b = np.full_like(a, 4)
b

array([4, 4])

In [38]:
#28
np.empty((3,9))

array([[4.47142519e-01, 7.76606361e-02, 9.97282012e-02, 5.92873110e-01,
        1.13646956e-02, 3.16259123e+00, 3.47224893e+00, 8.50273284e-01,
        4.62712965e-03],
       [1.20296798e+00, 1.11043075e-01, 9.27573448e-01, 1.78013506e-01,
        1.64132084e+00, 2.22841161e-03, 2.54430426e+00, 7.93725665e-02,
        3.80188526e+00],
       [2.92623721e+00, 1.43034009e-01, 3.09878087e+00, 4.92661744e+00,
        1.98686894e-01, 7.22759205e-01, 1.13970972e+00, 2.13756178e-01,
        2.94068148e-01]])

In [39]:
#29
np.empty_like(a)

array([ 891455647, 1070780931])

In [40]:
#30
np.full_like(a, 2) * np.nan

array([nan, nan])

In [41]:
#31

np.full(a.shape, np.nan)

array([nan, nan])

In [42]:
#32
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
#33
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
#34

a = np.array([1,3,4], dtype=int)

a.dtype


dtype('int32')

In [46]:
#35
b = np.array([3,8,9], dtype=a.dtype)
b.dtype

dtype('int32')

In [47]:
#36

a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [48]:
#37
a % 6 == 0

array([[[False, False, False],
        [False, False,  True],
        [False, False, False]],

       [[False, False,  True],
        [False, False, False],
        [False, False,  True]],

       [[False, False, False],
        [False, False,  True],
        [False, False, False]]])

In [49]:
#38
print(a)
a[(a%2==0) & (a%7==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([14])

In [50]:
#39
a.T

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [51]:
#40
a.T.T.T.T

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [52]:
#41
a.transpose()

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [53]:
#42
a.dot(b)

array([[ 46, 106, 166],
       [226, 286, 346],
       [406, 466, 526]])

In [54]:
#43
a.dot(a.T)

array([[[[  30,   84,  138],
         [  36,   90,  144],
         [  42,   96,  150]],

        [[  66,  201,  336],
         [  81,  216,  351],
         [  96,  231,  366]],

        [[ 102,  318,  534],
         [ 126,  342,  558],
         [ 150,  366,  582]]],


       [[[ 138,  435,  732],
         [ 171,  468,  765],
         [ 204,  501,  798]],

        [[ 174,  552,  930],
         [ 216,  594,  972],
         [ 258,  636, 1014]],

        [[ 210,  669, 1128],
         [ 261,  720, 1179],
         [ 312,  771, 1230]]],


       [[[ 246,  786, 1326],
         [ 306,  846, 1386],
         [ 366,  906, 1446]],

        [[ 282,  903, 1524],
         [ 351,  972, 1593],
         [ 420, 1041, 1662]],

        [[ 318, 1020, 1722],
         [ 396, 1098, 1800],
         [ 474, 1176, 1878]]]])

In [55]:
#44
a = np.array([-5,18,10,-2,-34,20])
np.abs(a)

array([ 5, 18, 10,  2, 34, 20])

In [56]:
#45
a = np.array([-5,18,10,-2,-34,20])
np.fabs(a)

array([ 5., 18., 10.,  2., 34., 20.])

In [57]:
#46
a = np.array([-5,18,10,-2,-34,20])
np.square(a)

array([  25,  324,  100,    4, 1156,  400], dtype=int32)

In [58]:
#47
a = np.array([-5,18,10,-2,-34,20])
np.exp(a)

array([6.73794700e-03, 6.56599691e+07, 2.20264658e+04, 1.35335283e-01,
       1.71390843e-15, 4.85165195e+08])

In [59]:
#48
a = np.array([-5,18,10,-2,-34,20])
np.ceil(a)

array([ -5.,  18.,  10.,  -2., -34.,  20.])

In [60]:
#49
a = np.array([-5,18,10,-2,-34,20])
np.floor(a)

array([ -5.,  18.,  10.,  -2., -34.,  20.])

In [61]:
#50
a = np.array([-5,18,10,-2,-34,20])
np.round(a)

array([ -5,  18,  10,  -2, -34,  20])